kubernetes_version: "1.29.0"

k8s_packages:
  - kubelet={{ kubernetes_version }}-*
  - kubeadm={{ kubernetes_version }}-*
  - kubectl={{ kubernetes_version }}-*

k8s_kernel_modules:
  - overlay
  - br_netfilter

k8s_sysctl:
  net.bridge.bridge-nf-call-iptables: 1
  net.bridge.bridge-nf-call-ip6tables: 1
  net.ipv4.ip_forward: 1
